title: A webpage experiment
author: amsyvah
email: s99...@gm..com
description: This is a simple webpage
theme: minima
# social links
twitter_username: willcreateatwitterhandle # DO NOT include the @ character, or else the build will fail!
github_username:  amsyvah # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
